# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/vivoz/Documents/WORK_FPGA/Xilinx/ver201604template/ver201604template.srcs/sources_1/bd/basicZturn/ip/basicZturn_auto_pc_0/basicZturn_auto_pc_0.xci
# IP: The module: 'basicZturn_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/vivoz/Documents/WORK_FPGA/Xilinx/ver201604template/ver201604template.srcs/sources_1/bd/basicZturn/ip/basicZturn_auto_pc_0/basicZturn_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'basicZturn_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/vivoz/Documents/WORK_FPGA/Xilinx/ver201604template/ver201604template.srcs/sources_1/bd/basicZturn/ip/basicZturn_auto_pc_0/basicZturn_auto_pc_0.xci
# IP: The module: 'basicZturn_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/vivoz/Documents/WORK_FPGA/Xilinx/ver201604template/ver201604template.srcs/sources_1/bd/basicZturn/ip/basicZturn_auto_pc_0/basicZturn_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'basicZturn_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
