struct BtmTempSimTyp
{
    float               BtmTrJncTempAL;
    float               BtmTrJncTempAU;
    float               BtmTrJncTempBL;
    float               BtmTrJncTempBU;
    float               BtmTrJncTempCL;
    float               BtmTrJncTempCU;
	float               BtmTrJncTempDL;
    float               BtmTrJncTempDU;

    float               BtmDjncTempAL;
    float               BtmDjncTempAU;
    float               BtmDjncTempBL;
    float               BtmDjncTempBU;
    float               BtmDjncTempCL;
    float               BtmDjncTempCU;
	float               BtmDjncTempDL;
    float               BtmDjncTempDU;
    // Max Jnc Temperature
    float               BtmTrJncTemp;
    float               BtmDjncTemp;
    
};
