/*=============================================================================
* Product:     GE Power Conversion Using MACC Control
* Host:        DSPX Running TMS320C31
* File:        Y1BRTHM.H
* Language:    TI 'C'
* Copyright:   1996..1998 GE Industrial Control Systems, Salem VA
*
* Abstract:  Constants, function prototypes for bridge thermal model.
*
* Functions in module:  None
*
*==============================================================================
* 961030 DGR  Initial create.
* 030204 SAB  Branch from 'rotor' and include in 'combo'
* 030215 SAB  Remove fan speed stuff
* 030219 SAB  Add temperature max/min vars
* 030221 SAB  Thermal model improvements and name changes
* 030222 SAB  More thermal fault changes
* 030224 SAB  Add EE mirrors for over-temp thresholds
* 030225 SAB  Remove RTD flags
* 040223 SAB  Remove un-used vars
* 040224 SAB  Remove more un-used vars.
* 050408 IB   Add Can OT alarm flags
* 051212 BAG  move BICS_Temp_Vco type def from Y1brthm.c30 and y2brthm.c30 to Y1brthm.h for windows simulator
* 061206 SAB  Add prototypes
* 060316 IB   Add R_OTTrpDlySm
*==============================================================================
* Last Mod: March 16, 2005 06:40:14PM
*==============================================================================
*/


#ifndef  Y1BRTHM_H
#define  Y1BRTHM_H





#endif
