# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/rate.xdc

# Block Designs: bd/basicZturn/basicZturn.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basicZturn || ORIG_REF_NAME==basicZturn}]

# IP: bd/basicZturn/ip/basicZturn_processing_system7_0_0/basicZturn_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basicZturn_processing_system7_0_0 || ORIG_REF_NAME==basicZturn_processing_system7_0_0}]

# IP: bd/basicZturn/ip/basicZturn_axi_gpio_0_0/basicZturn_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basicZturn_axi_gpio_0_0 || ORIG_REF_NAME==basicZturn_axi_gpio_0_0}]

# IP: bd/basicZturn/ip/basicZturn_ps7_0_axi_periph_0/basicZturn_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basicZturn_ps7_0_axi_periph_0 || ORIG_REF_NAME==basicZturn_ps7_0_axi_periph_0}]

# IP: bd/basicZturn/ip/basicZturn_rst_ps7_0_100M_0/basicZturn_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basicZturn_rst_ps7_0_100M_0 || ORIG_REF_NAME==basicZturn_rst_ps7_0_100M_0}]

# IP: bd/basicZturn/ip/basicZturn_axi_gpio_1_0/basicZturn_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basicZturn_axi_gpio_1_0 || ORIG_REF_NAME==basicZturn_axi_gpio_1_0}]

# IP: bd/basicZturn/ip/basicZturn_xbar_0/basicZturn_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basicZturn_xbar_0 || ORIG_REF_NAME==basicZturn_xbar_0}]

# IP: bd/basicZturn/ip/basicZturn_axi_gpio_2_0/basicZturn_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basicZturn_axi_gpio_2_0 || ORIG_REF_NAME==basicZturn_axi_gpio_2_0}]

# IP: bd/basicZturn/ip/basicZturn_axi_iic_0_0/basicZturn_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basicZturn_axi_iic_0_0 || ORIG_REF_NAME==basicZturn_axi_iic_0_0}]

# IP: bd/basicZturn/ip/basicZturn_PWM_0_0/basicZturn_PWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basicZturn_PWM_0_0 || ORIG_REF_NAME==basicZturn_PWM_0_0}]

# IP: bd/basicZturn/ip/basicZturn_addition_0_0/basicZturn_addition_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basicZturn_addition_0_0 || ORIG_REF_NAME==basicZturn_addition_0_0}]

# IP: bd/basicZturn/ip/basicZturn_axi_uartlite_0_0/basicZturn_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basicZturn_axi_uartlite_0_0 || ORIG_REF_NAME==basicZturn_axi_uartlite_0_0}]

# IP: bd/basicZturn/ip/basicZturn_xadc_wiz_0_0/basicZturn_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basicZturn_xadc_wiz_0_0 || ORIG_REF_NAME==basicZturn_xadc_wiz_0_0}]

# IP: bd/basicZturn/ip/basicZturn_auto_pc_0/basicZturn_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basicZturn_auto_pc_0 || ORIG_REF_NAME==basicZturn_auto_pc_0}]

# XDC: bd/basicZturn/basicZturn_ooc.xdc
