# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ver201604template/ver201604template.srcs/sources_1/bd/basicZturn/ip/basicZturn_xadc_wiz_0_0/basicZturn_xadc_wiz_0_0.xci
# IP: The module: 'basicZturn_xadc_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ver201604template/ver201604template.srcs/sources_1/bd/basicZturn/ip/basicZturn_xadc_wiz_0_0/basicZturn_xadc_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'basicZturn_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/ver201604template/ver201604template.srcs/sources_1/bd/basicZturn/ip/basicZturn_xadc_wiz_0_0/basicZturn_xadc_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'basicZturn_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/ver201604template/ver201604template.srcs/sources_1/bd/basicZturn/ip/basicZturn_xadc_wiz_0_0/basicZturn_xadc_wiz_0_0.xci
# IP: The module: 'basicZturn_xadc_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ver201604template/ver201604template.srcs/sources_1/bd/basicZturn/ip/basicZturn_xadc_wiz_0_0/basicZturn_xadc_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'basicZturn_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/ver201604template/ver201604template.srcs/sources_1/bd/basicZturn/ip/basicZturn_xadc_wiz_0_0/basicZturn_xadc_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'basicZturn_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
